=== Kapetto-o/KYaR_1Sem/laboratory_work_12/Ex3/xsd/university.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs ="http://www.w3.org/2001/XMLSchema">
<xs:element name="university">
<xs:complexType>
<xs:sequence>
    <xs:element name="head">
    <xs:complexType>
    <xs:sequence>
        <xs:element name="univ" type="xs:string"/>
        <xs:element name="BSTU" type="xs:string"/>
    </xs:sequence>
    </xs:complexType>
    </xs:element>
    <xs:element name="main">
    <xs:complexType>
    <xs:sequence>
        <xs:element name="facult" type="xs:string"/>
        <xs:element name="facultiesName">
        <xs:complexType>
        <xs:sequence>
            <xs:element name="FIT" type="xs:string"/>
            <xs:element name="FF" type="xs:string"/>
            <xs:element name="CTE" type="xs:string"/>
            <xs:element name="PaM" type="xs:string"/>
        </xs:sequence>
        </xs:complexType>
        </xs:element>
    </xs:sequence>
    </xs:complexType>
    </xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== Kapetto-o/KYaR_1Sem/laboratory_work_12/Ex3/Ex3.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="css/Ex3.css"?>
<university 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="xsd/university.xsd">
    <head>
        <univ>Университет:</univ>
        <BSTU>БГТУ</BSTU>
    </head>
    <main>
    <facult>Факультеты:</facult>
    <facultiesName>
        <FIT>ФИТ</FIT>
        <FF>ЛХФ</FF>
        <CTE>ХТиТ</CTE>
        <PaM>ПиМ</PaM>
    </facultiesName>
    </main>
</university>
